export { api } from './client'
export { authService } from './auth'
export type { User, LoginRequest, LoginResponse, UpdateProfileRequest, ChangePasswordRequest } from './auth'
export { patientService } from './patients'
export type { Patient, PatientListParams, PaginatedPatients, CreatePatientRequest, CreatePatientResponse, PromSendRequest } from './patients'
export { surgeryService } from './surgery'
export type { ClinicalData, OutcomeData } from './surgery'
export { dashboardService } from './dashboard'
export type { DashboardData, DashboardStats, VasOdiDataPoint, SurgeryTypeDistribution, StatisticsData, ApproachComparison, PatientOutcomePoint, RecentFollowup } from './dashboard'
export { reportService } from './reports'
export type { ReportData, ReportParams, ReportSummary, MonthlyDataPoint, SurgeryOutcome } from './reports'
export { surveyService } from './survey'
export type { SurveyStatus, SurveyVerifyRequest, SurveyVerifyResponse, SurveyQuestion, SurveyQuestionsResponse, SurveySubmitResponse } from './survey'
